In [1]:
import pandas as pd
import numpy as np
import os
import pyreadstat

In [10]:
BD1,meta1 = pyreadstat.read_sav(r"C:\Users\User\OneDrive - Universidad Torcuato Di Tella\2. PC TUF reforzada\MINEDU 2026\Repositorios\MINEDU-2026-05-INFOGRAFIA-EDDIR-DRE-UGEL-2023-2024\data\Consolidado_DGP-JGP_01.04.2026_final.sav")
BD2 = pd.read_excel(r"C:\Users\User\OneDrive - Universidad Torcuato Di Tella\2. PC TUF reforzada\MINEDU 2026\Repositorios\MINEDU-2026-05-INFOGRAFIA-EDDIR-DRE-UGEL-2023-2024\data\Resultados_DirUgel_2026.xlsx",
sheet_name="Resultados", dtype = {"DocumentoIdentidad":str})

In [ ]:
BD1["CondicionFinal"].value_counts(dropna=False)

CondicionFinal
Aprobado                                                                105
No evaluado por renuncia formal al cargo en el que ha sido designado      4
Desaprobado                                                               3
Name: count, dtype: int64

In [15]:
BD2["CondicionFinal"].value_counts(dropna=False)

CondicionFinal
Aprobado       73
Desaprobado    18
Name: count, dtype: int64

In [26]:
BD1.columns

Index(['IDLista', 'IDRegion', 'DesRegion', 'IDDreUgel', 'DreUgel', 'Documento',
       'ApePaternoEvaluado', 'ApeMaternoEvaluado', 'NombreEvaluado',
       'CorreoElectronico', 'Celular', 'IDCargo', 'DesCargo', 'IDTipoUnidad',
       'DesTipoUnidad', 'EstadoEvaluacion', 'EVAL', 'SeRealizoEvaluacion',
       'DesempenoEfectivo', 'OR1_ptje', 'OR2_ptje', 'OR3_ptje', 'LC1_ptje',
       'LC2_ptje', 'LC3_ptje', 'CS1_ptje', 'CS2_ptje', 'PRG_puntaje',
       'PCT_puntaje', 'Puntaje_Final', 'Condicion1', 'Condicion2',
       'Condicion3', 'CondicionFinal', 'IDA', 'sex', 'fecha_nac', 'fecha_pub',
       'edad', 'edquin', 'grupedad'],
      dtype='object')

In [27]:
BD2.columns

Index(['IDLista', 'IDRegion', 'Region', 'IDDreUgel', 'DreUgel', 'Cargo',
       'DocumentoIdentidad', 'NombreCompleto', 'EstadoEvaluacion',
       'IDEvaluacion', 'SeRealizoEvaluacion', 'DesempenoEfectivo',
       'Calificacion_Criterio1', 'Calificacion_Criterio2',
       'Calificacion_Criterio3', 'Calificacion_Criterio4',
       'Calificacion_Criterio5', 'Calificacion_Criterio6',
       'Calificacion_Criterio7', 'Calificacion_Criterio8',
       'Calificacion_Criterio9', 'Calificacion_Criterio10', 'OR1_ptje',
       'OR2_ptje', 'OR3_ptje', 'LC1_ptje', 'LC2_ptje', 'LC3_ptje', 'CS1_ptje',
       'CS2_ptje', 'PRG_puntaje', 'PCT_puntaje', 'Puntaje_Final', 'Condicion1',
       'Condicion2', 'Condicion3', 'CondicionFinal'],
      dtype='object')

In [29]:
list(set(BD1.columns).intersection(set(BD2.columns)))

['Condicion3',
 'IDLista',
 'DreUgel',
 'CS2_ptje',
 'EstadoEvaluacion',
 'IDDreUgel',
 'Condicion1',
 'SeRealizoEvaluacion',
 'IDRegion',
 'Condicion2',
 'CS1_ptje',
 'OR1_ptje',
 'OR2_ptje',
 'LC3_ptje',
 'Puntaje_Final',
 'PCT_puntaje',
 'LC1_ptje',
 'CondicionFinal',
 'LC2_ptje',
 'OR3_ptje',
 'PRG_puntaje',
 'DesempenoEfectivo']

## Union de bases

In [42]:
cols_bd1 = [
    'IDLista',
    'IDRegion',
    'DesRegion',
    'IDDreUgel',
    'DreUgel',
    'Documento',
    'DesCargo',
    'EstadoEvaluacion',
    'SeRealizoEvaluacion',
    'DesempenoEfectivo',
    'OR1_ptje',
    'OR2_ptje',
    'OR3_ptje',
    'LC1_ptje',
    'LC2_ptje',
    'LC3_ptje',
    'CS1_ptje',
    'CS2_ptje',
    'PRG_puntaje',
    'PCT_puntaje',
    'Puntaje_Final',
    'Condicion1',
    'Condicion2',
    'Condicion3',
    'CondicionFinal'
]

BD1_f = BD1[cols_bd1].copy()

In [43]:
cols_bd2 = [
    'IDLista',
    'IDRegion',
    'Region',
    'IDDreUgel',
    'DreUgel',
    'DocumentoIdentidad',
    'Cargo',
    'EstadoEvaluacion',
    'SeRealizoEvaluacion',
    'DesempenoEfectivo',
    'OR1_ptje',
    'OR2_ptje',
    'OR3_ptje',
    'LC1_ptje',
    'LC2_ptje',
    'LC3_ptje',
    'CS1_ptje',
    'CS2_ptje',
    'PRG_puntaje',
    'PCT_puntaje',
    'Puntaje_Final',
    'Condicion1',
    'Condicion2',
    'Condicion3',
    'CondicionFinal'
]

BD2_f = BD2[cols_bd2].copy()

In [44]:
BD2_f = BD2_f.rename(columns={
    "Region": "DesRegion",
    "DocumentoIdentidad": "Documento",
    "Cargo": "DesCargo"
})

In [45]:
BD1_f["FUENTE"] = "DGP_JPG"
BD2_f["FUENTE"] = "DIR_UGEL"

In [46]:
BD1_f.columns.equals(BD2_f.columns)

True

In [47]:
BD_final = pd.concat(
    [BD1_f, BD2_f],
    ignore_index=True
)

In [50]:
BD_final["CondicionFinal"].value_counts(dropna=False)

CondicionFinal
Aprobado                                                                178
Desaprobado                                                              21
No evaluado por renuncia formal al cargo en el que ha sido designado      4
Name: count, dtype: int64

## Métricas

In [53]:
BD_final.groupby("DesCargo")["CondicionFinal"].value_counts(dropna=False).reset_index()

,DesCargo,CondicionFinal,count
0,Director de UGEL,Aprobado,73
1,Director de UGEL,Desaprobado,18
2,Director de gestión pedagógica de la DRE,Aprobado,13
3,Jefe de gestión pedagógica de la UGEL,Aprobado,92
4,Jefe de gestión pedagógica de la UGEL,No evaluado por renuncia formal al cargo en el...,4
5,Jefe de gestión pedagógica de la UGEL,Desaprobado,3

In [64]:
print(
    pd.crosstab(
        BD_final["CondicionFinal"],
        BD_final["DesempenoEfectivo"],
        margins=True,
        dropna=False
    ).to_markdown(
        tablefmt="github"
    )
)

| CondicionFinal                                                       |   - |   No |   Sí |   All |
|----------------------------------------------------------------------|-----|------|------|-------|
| Aprobado                                                             |   0 |    0 |  178 |   178 |
| Desaprobado                                                          |   0 |    7 |   14 |    21 |
| No evaluado por renuncia formal al cargo en el que ha sido designado |   4 |    0 |    0 |     4 |
| All                                                                  |   4 |    7 |  192 |   203 |

In [54]:
BD_final

,IDLista,IDRegion,DesRegion,IDDreUgel,DreUgel,Documento,DesCargo,EstadoEvaluacion,SeRealizoEvaluacion,DesempenoEfectivo,...,CS1_ptje,CS2_ptje,PRG_puntaje,PCT_puntaje,Puntaje_Final,Condicion1,Condicion2,Condicion3,CondicionFinal,FUENTE
0,15465,8,CUSCO,255,UGEL PICHARI KIMBIRI,23937132,Jefe de gestión pedagógica de la UGEL,NO EVALUADO,No,-,...,,,0.000,0.000,0.00,,,,No evaluado por renuncia formal al cargo en el...,DGP_JPG
1,15464,8,CUSCO,128,UGEL LA CONVENCIÓN,25319623,Jefe de gestión pedagógica de la UGEL,NO EVALUADO,No,-,...,,,0.000,0.000,0.00,,,,No evaluado por renuncia formal al cargo en el...,DGP_JPG
2,15485,12,JUNÍN,158,UGEL PANGOA,19937777,Jefe de gestión pedagógica de la UGEL,NO EVALUADO,No,-,...,,,0.000,0.000,0.00,,,,No evaluado por renuncia formal al cargo en el...,DGP_JPG
3,15537,24,TACNA,125,UGEL JORGE BASADRE,04748110,Jefe de gestión pedagógica de la UGEL,NO EVALUADO,No,-,...,,,0.000,0.000,0.00,,,,No evaluado por renuncia formal al cargo en el...,DGP_JPG
4,15479,11,ICA,73,UGEL CHINCHA,21845903,Jefe de gestión pedagógica de la UGEL,APROBADO,Sí,Sí,...,4,3,4.000,3.125,3.47,Cumple,Cumple,Cumple,Aprobado,DGP_JPG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198,16849,13,LA LIBERTAD,49,UGEL BOLÍVAR,19099968,Director de UGEL,APROBADO,Sí,Sí,...,3,4,2.500,3.375,3.02,Cumple,Cumple,Cumple,Aprobado,DIR_UGEL
199,16850,13,LA LIBERTAD,126,UGEL JULCÁN,19090219,Director de UGEL,DESAPROBADO,Sí,Sí,...,3,2,3.000,2.125,2.47,No cumple,Cumple,Cumple,Desaprobado,DIR_UGEL
200,16851,13,LA LIBERTAD,152,UGEL PACASMAYO,19082958,Director de UGEL,DESAPROBADO,Sí,Sí,...,3,2,3.555,1.875,2.54,No cumple,Cumple,Cumple,Desaprobado,DIR_UGEL
201,16856,15,LIMA METROPOLITANA,14,UGEL 04 COMAS,32264712,Director de UGEL,APROBADO,Sí,Sí,...,4,3,2.800,3.250,3.07,Cumple,Cumple,Cumple,Aprobado,DIR_UGEL
202,16864,17,LORETO,206,UGEL UCAYALI-CONTAMANA,05710946,Director de UGEL,DESAPROBADO,Sí,No,...,1,3,2.666,1.250,1.81,No cumple,No cumple,No cumple,Desaprobado,DIR_UGEL

### Infografia

In [68]:
BD_final[BD_final["CondicionFinal"]!="No evaluado por renuncia formal al cargo en el que ha sido designado"].groupby("DesCargo")["CondicionFinal"].value_counts(dropna=False).reset_index()

                                   DesCargo CondicionFinal  count
0                          Director de UGEL       Aprobado     73
1                          Director de UGEL    Desaprobado     18
2  Director de gestión pedagógica de la DRE       Aprobado     13
3     Jefe de gestión pedagógica de la UGEL       Aprobado     92
4     Jefe de gestión pedagógica de la UGEL    Desaprobado      3

In [72]:
cols = [
    "OR1_ptje", "OR2_ptje", "OR3_ptje",
    "LC1_ptje", "LC2_ptje", "LC3_ptje",
    "CS1_ptje", "CS2_ptje"
]

tmp = (
    BD_final[
        BD_final["CondicionFinal"] !=
        "No evaluado por renuncia formal al cargo en el que ha sido designado"
    ][cols]
    .apply(pd.to_numeric, errors="coerce")
)

tmp.apply(
    lambda x: x.value_counts(dropna=False)
).fillna(0).astype(int)

,OR1_ptje,OR2_ptje,OR3_ptje,LC1_ptje,LC2_ptje,LC3_ptje,CS1_ptje,CS2_ptje
1.0,4,7,9,13,19,5,16,5
2.0,17,23,28,34,35,24,72,20
3.0,53,55,56,67,62,64,44,57
4.0,121,110,102,85,83,103,67,117
NaN,4,4,4,0,0,3,0,0